import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;

public class CenterPanel extends JPanel {

    SingleTrack singleTrack;
    SingleTrack singleTrack1;
    SingleTrack singleTrack2;
    SingleTrack singleTrack3;
    SingleTrack singleTrack4;
    SingleTrack singleTrack5;
    SingleTrack singleTrack6;
    SingleTrack singleTrack7;
    SingleTrack singleTrack8;
    SingleTrack singleTrack9;
    SingleTrack singleTrack10;
    SingleTrack singleTrack11;
    SingleTrack singleTrack12;
    SingleTrack singleTrack13;
    SingleTrack singleTrack14;
    SingleTrack singleTrack15;
    SingleTrack singleTrack16;
    SingleTrack singleTrack17;
    SingleTrack singleTrack18;
    SingleTrack singleTrack19;
    SingleTrack singleTrack20;
    SingleTrack singleTrack21;
    SingleTrack singleTrack22;
    SingleTrack singleTrack23;
    SingleTrack singleTrack24;
    SingleTrack singleTrack25;
    SingleTrack singleTrack26;
    SingleTrack singleTrack27;
    SingleTrack singleTrack28;

    public CenterPanel (){
        singleTrack = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack1 = new SingleTrack("/camera.png" , " l"  ,"s" , "q");
        singleTrack2 = new SingleTrack("/camera.png" , " g"  ,"g" , "t");
        singleTrack3 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack4 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack5 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack6 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack7 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack8 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack9 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack10 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack11 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack12 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack13 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack14 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack15 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack16 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack17 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack18 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack19 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack20 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack21 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack22 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack23 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack24 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack25 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack26 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack27 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        singleTrack28 = new SingleTrack("/camera.png" , " g"  ,"d" , "o");
        WrapLayout f = new WrapLayout(WrapLayout.LEFT);
        this.setLayout(f);
        this.add(singleTrack);
        this.add(singleTrack1);
        this.add(singleTrack2);
        this.add(singleTrack3);
        this.add(singleTrack4);
        this.add(singleTrack5);
        this.add(singleTrack6);
        this.add(singleTrack7);
        this.add(singleTrack8);
        this.add(singleTrack9);
        this.add(singleTrack10);
        this.add(singleTrack11);
        this.add(singleTrack12);
        this.add(singleTrack13);
        this.add(singleTrack14);
        this.add(singleTrack15);
        this.add(singleTrack16);
        this.add(singleTrack17);
        this.add(singleTrack18);
        this.add(singleTrack19);
        this.add(singleTrack20);
        this.add(singleTrack21);
        this.add(singleTrack22);
        this.add(singleTrack23);
        this.add(singleTrack24);
        this.add(singleTrack25);
        this.add(singleTrack26);
        this.add(singleTrack27);
        this.add(singleTrack28);

    }
}
